### ISSUE TITLE
Repeat macros with dot

### ISSUE THREAD

**Issue by ntrrgc** [tpope/vim-repeat#20]
Many times I write a vim macro to do something and then I want to execute it here and there, but `@@` is a somewhat inconvenient mapping.

IMHO if my last edit command was to execute a macro, dot should execute that macro, but that is not how vim works. It would be great if this plugin could exhibit this behavior with the dot, just like it does with other plugins' commands.

**Comment by schlichtanders** [comment]
I would also appreciate this feature
and it seems intuitive to include it in this plugin

is it too cumbersome to implement it?

**Comment by tpope** [comment]
No idea, please investigate.

**Comment by Alok** [comment]
@tpope Did you ever end up experimenting with adding support for macros?

**Comment by HaleTom** [comment]
For other googlers, use `@@` as a work-around to repeat the last macro.

[Subscribing for updates]

**Comment by gilesbowkett** [comment]
thanks @HaleTom! I knew that already, in theory, somewhere in the back of my head, but Google did indeed take me here, and you totally saved me some hassle.

**Comment by alphaCTzo7G** [comment]
The great thing about `.` is its a single operator.. especially you want to repeat the macro a lot of times.. If I use `@@` after recording the macro.. will a `.` repeat the `@@`?

**Comment by tpope** [comment]
With fresh eyes, this idea seems kind of absurd. Record a macro like `q@.q`. Now call it with `@a`. That just redid the `.`. What happens now when you call `.` to repeat the macro with `.` in it?
