### ISSUE TITLE
breaks macros containing dot-repeat

### ISSUE THREAD

**Issue by justinmk** [tpope/vim-repeat#23]
On Windows gvim with repeat.vim, replaying a macro that contains a dot-repeat invocation will insert the `@.` register instead of repeating. 

confirmed on:

- [msys2](http://sourceforge.net/projects/msys2/files/Alpha-versions/) Vim 7.4.183.
- MacVim 7.4.103
- Windows vim.org 7.4.0 build
- [this 64-bit 7.4.192 build](https://bintray.com/veegee/generic/vim_x64)
- [this 32-bit 7.4.205 build](http://tuxproject.de/projects/vim/).

Minimal steps to reproduce:

- start gvim.exe with `gvim.exe -N -u NONE`
- `:source repeat.vim`
- insert this text:

```
a b c
a b c
```

- on line 1 column 1, perform: `qqdw.ifoo<esc>q`
- on line 2 column 1, perform: `@q`
- the result:

```
fooc
fofooob c
```

Which is wrong. The expected result is:

```
fooc
fooc
```

This could be a bug in `feedkeys()`...

**Comment by justinmk** [comment]
vim_dev has given some attention to this issue, and it appears that there is no general solution for feedkeys(). So here's a PR that uses `:norm` for Vim >= 7.3.100: https://github.com/tpope/vim-repeat/pull/36

**Comment by wellle** [comment]
Actually `feedkeys` just got a new flag `i` that could now be used: [Patch 7.4.601](https://groups.google.com/forum/?fromgroups#!topic/vim_dev/qxf0yYZu52Y)

**Comment by inkarkat** [comment]
@wellle: But I hope you'll agree that the existing `:normal` is more straightforward, so there's no need to change yet again.

**Comment by justinmk** [comment]
@wellle send a PR!

**Comment by wellle** [comment]
@justinmk: #39
