### ISSUE TITLE
repeat has stopped handling speeddating correctly

### ISSUE THREAD

**Issue by chiphogg** [tpope/vim-repeat#45]
Ever since ad89be240fe2eb78cd7e5ff47293faa548c03ee8, [vim-speeddating](https://github.com/tpope/vim-speeddating) repetition is broken.  Here's how to reproduce.

1.  In a new buffer, enter `2015-04-01`.
2.  Go to the end of this string, and type `7<C-A>` to increment this date by one week.  (Current text: `2015-04-08`.)
3.  Type `.` to repeat the previous command.  The expected result is that the text reads `2015-04-15`; instead, it reads `2015-04-09` (incrementing by one day instead of 7).

    Additionally, a count of `7` is pending (which you can see if `'showcmd'` is active).  Looks like things got a bit out of order?

**Comment by tpope** [comment]
Given that commit is nothing but version checks, maybe consider sharing your actual version?

**Comment by chiphogg** [comment]
Maybe you were a little hasty when you checked it?  That version isn't _just_ version checks; it also changes an option passed to `feedkeys()`.

I was careful and thorough with my bug report.  The correct behaviour occurs with the previous commit, but the incorrect behaviour occurs starting with this commit.

**Comment by wellle** [comment]
I can reproduce the bug. I will try to look into it by the end of the week.

**Comment by chiphogg** [comment]
Thanks for looking into it!

**Comment by justinmk** [comment]
I noticed this same problem (`[count].` repeat only repeats once) with https://github.com/justinmk/vim-sneak.

**Comment by wellle** [comment]
Should be fixed with #46. Thanks for pinging me :+1:
