### ISSUE TITLE
fugitive-vim, vim-unimpaired and vim-repeat (repeat of `]q` not working)

### ISSUE THREAD

**Issue by patrickdavey** [tpope/vim-repeat#54]
I am trying to step through the history of a file in a git repo, and I expected the following to work for me:

1. Open the file in vim
2. Type `:Glog` to load the git history of the file into quickfix (works)
3. Type `]q` to step to the next version of the file (works)
4. Type `.` to step again to the next version of the file (doesn't work)

I might be misunderstanding whether vim-repeat is supposed to work with vim-unimpaired, but it was my assumption that the steps above would work.

What does happen is that command mode is started and I get a command line like the following: (browsing my .vimrc)

`: 477eeb94566ddba99aec929f33afa563b5c29624:.vimrc`

So it looks like it's trying.. just can't do it.  Not quite sure whether this issue should be on here or on fugitive.vim so happy to move it around if needs be.

I also pared my .vimrc back to just pathogen, and the plugins to just those three, no difference.  I also got a couple of friends to try and they saw the same behaviour.

Happy to have a go at fixing it if I could have a pointer in the right direction!

**Comment by tpope** [comment]
`.` is to repeat a *change*, not any arbitrary command.
