### ISSUE TITLE
saving on TextChanged event breaks vim-repeat

### ISSUE THREAD

**Issue by swalladge** [tpope/vim-repeat#59]
Minimal vimrc displaying this behaviour:

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
call plug#end()
augroup save
  au!
  au TextChanged ?* silent! wa
augroup END
```

An example of what happens:

1. perform `ysiw)` to surround a word with parentheses.
2. press `.` to repeat the surround on another word
3. the cursor appears at the bottom of the screen, waiting for the character to surround the word with (as if you did `ysiw`
4. pressing `)` completes the surround as expected.

I haven't read the source of vim-repeat, so not sure exactly why this might be happening. The help for `TextChanged` says that it's fired when `b:changedtick` is changed, so I'm guessing it saves the file halfway through the initial command, which makes only part of the commend registered with vim-repeat somehow...

**Comment by bluz71** [comment]
Today I decided to figure out why does *vim-repeat* not work for me. Yes, basically due to this.

My autocmd is similar (a Vim hack auto-save):

```
augroup autoSave
    autocmd!
    autocmd TextChanged,InsertLeave,FocusLost * silent! wall
augroup END
```

In the meantime recording a macro is the way to go to do *vim-surround* repeats for those who do the above style `TextChange` tricks: `qq` then `cs"'` then `q` then lastly `Q` (a mapping of mine) to run the macro.

Many thanks.

**Comment by swalladge** [comment]
This reminds me - I should add that this only breaks with `tpope/vim-surround` and `tpope/vim-repeat` together.  - ie. saving on textchanged breaks repeating vim-surround actions.

Interestingly, (vim-sandwich)[https://github.com/machakann/vim-sandwich] works fine with vim-repeat and saving on textchanged. Minimal vimrc that works fine:

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-repeat'
Plug 'machakann/vim-sandwich'
call plug#end()

" for vim-surround like mappings
runtime macros/sandwich/keymap/surround.vim

augroup vimrc
  autocmd!
  autocmd TextChanged ?* silent! wa
augroup END
```

**Comment by ironhouzi** [comment]
@swalladge this is not entirely correct. `vim-repeat` is also needed for other plugins developed by @tpope. `vim-commentary` comes to mind, but probably others as well.

**Comment by swalladge** [comment]
>  vim-repeat is also needed for other plugins developed by @tpope. vim-commentary comes to mind, but probably others as well.

@ironhouzi yes it's needed for many plugins, but it doesn't break with all plugins that use it. That's the reason why I'm not sure if the issue is in vim-repeat, or the issue is with how other plugins use it.

**Comment by tpope** [comment]
FYI The HEAD version of commentary.vim no longer requires repeat.vim, which might be the source of some confusion. If you're looking for another plugin to test against, try `[e` and `[<Space>` in unimpaired.vim.

**Comment by bluz71** [comment]
Worth noting, the [vim-auto-save](https://github.com/907th/vim-auto-save) plugin does work with *vim-repeat*.

So if your only need to use the `TextChanged` event was to initiate auto-saving (as I was) then I suggest just using the vim-auto-save plugin instead. Somehow it avoids the clash with *vim-repeat* that [this snippet](https://github.com/tpope/vim-repeat/issues/59#issuecomment-310556519) had.

These are the settings I use:

```viml
Plug '907th/vim-auto-save'
let g:auto_save        = 1
let g:auto_save_silent = 1
let g:auto_save_events = ["InsertLeave", "TextChanged", "FocusLost"]
```

Thanks to @tpope for all your contributions.

**Comment by swalladge** [comment]
@bluz71 great find! I believe I have found a lead based on this. `vim-auto-save` uses `nested` in the autocmd call to recurse autocmds when calling `:w` or `:e` from inside the autocmd. `:h autocmd-nested` for more info. Modifying my original minimal vimrc to include nested in the autocmd fixes the original issue:

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
call plug#end()
augroup save
  au!
  au TextChanged ?* silent! wa
augroup END
```

Now it remains to be seen why this works...

**Comment by swalladge** [comment]
Update: vim-repeat relies on the `BufWrite*` events in https://github.com/tpope/vim-repeat/blob/8106e142dfdc278ff3eaaadd7b362ad7949d4357/autoload/repeat.vim#L141 .  If the file is saved from inside an autocmd that isn't nested, those events will not be fired and `g:repeat_tick` will not be updated. It sounds like something similar to #63 where `b:changedtick` is suddenly a value that vim-repeat isn't expecting.

**Comment by MahbubAlam231** [comment]
Is there a way to make vim-repeat work along with `TextChanged` and `TextChangedI`?

**Comment by swalladge** [comment]
@MahbubAlam231 see my [previous comment](https://github.com/tpope/vim-repeat/issues/59#issuecomment-402010187) for a work around (add `nested` to the autocmd).

**Comment by MahbubAlam231** [comment]
Thanks @swalladge , it works. I do not quite understand vim script yet, I read `:h autocmd-nested`, didn't get what's going on, can you please explain what is this nested thing and why it works?

**Comment by tpope** [comment]
Okay, makes sense, the old autocommand was broken and adding `nested` fixes it. I don't think this is a repeat.vim bug.
