### ISSUE TITLE
consider a new git tag / release

### ISSUE THREAD

**Issue by anthraxx** [tpope/vim-repeat#61]
It would be great to get a new git tag / release, the last one is from 2013... even through not a crazy amount of development happened but still some fixes and stuff got merged. It would be cool to simply tag a new one so people adopt the latest patches.

**Comment by anthraxx** [comment]
@tpope ping, please :smile_cat:

**Comment by tpope** [comment]
At least that means the release notes were easy.

**Comment by anthraxx** [comment]
@tpope thanks :)
