### ISSUE TITLE
`.` could not repeat

### ISSUE THREAD

**Issue by MahbubAlam231** [tpope/vim-repeat#64]
I performed the operation-- `ysiw"`
I then went to another word and pressed `.` , it did not repeat, it performed `ysiw` and waited for me to to press `"`
It happened with all other similar operations. What's wrong?

**Comment by ironhouzi** [comment]
I've been experiencing similar issues. Can I ask what version of Vim you're using?

**Comment by tpope** [comment]
You two have repeat.vim installed, correct?

**Comment by ironhouzi** [comment]
Yes, it's an issue of #59 for me.

**Comment by tpope** [comment]
That was a dumb question on my part, thought this was the surround repo @MahbubAlam231 does #59 fit for you too?

**Comment by MahbubAlam231** [comment]
Yes, #59 fit for me too, though I can't tell if TextChanged event is the only one causing the problem.

**Comment by tpope** [comment]
Closing as a dupe of #59 then.
