### ISSUE TITLE
Repeating with vim-surround not working properly

### ISSUE THREAD

**Issue by kkoomen** [tpope/vim-repeat#76]
**Current behavior**

Input:

```html
<span class="test">
   <!--cursor-here-->Lorem ipsum.
</span>

<span class="test">
  Lorem ipsum.
</span>
```

When pressing `cst<div` it will change the first item correctly. If I go to the second `<span>` it will remove all the attributes.

Output:

```html
<div class="test">
   Lorem ipsum.
</div>

<div>
  Lorem ipsum.
</div>
```

**Expected behavior**

```html
<div class="test">
  Lorem ipsum.
</div>

<div class="test">
  Lorem ipsum.
</div>
```

**Comment by tpope** [comment]
Repeat doesn't even know what HTML *is*, it's definitely not the plugin to blame here.

**Comment by kkoomen** [comment]
I didn't say it knows what html is. Your plugin it to blame for it, because apparently it doesn't seem to mimmick `cst<` in the correct way, otherwise the result would be the same.

**Comment by tpope** [comment]
Repeat just repeats what Surround tells it to repeat. If it's repeating the wrong thing it was told the wrong thing.

P.S. take that "your plugin is to blame for it" and shove it up your ass.
