### ISSUE TITLE
Is there a concrete way to replace . to other key? Documentation is unclear...

### ISSUE THREAD

**Issue by AndresMpa** [tpope/vim-repeat#87]
I've been reading issues and I don't get at all how to change . mapping, . is really anoying, it's too far from other keys in my keyboard... Then README doesn't explain how to change that... Could it be explain there in a concrete way?

**Comment by AndresMpa** [comment]
I've been reading issues and I don't get all how to change . mapping . is really anoying... Then the README doesn't explain how to change that... Could it be explain there in a concrete way?

**Comment by svermeulen** [comment]
I think you can just add maps to the `<plug>` versions and then repeat-vim will not add the `.` mappings.  Eg:

```
nmap a <Plug>(RepeatDot)
nmap b <Plug>(RepeatUndo)
nmap B <Plug>(RepeatUndoLine)
nmap c <Plug>(RepeatUndoLine)
```
